### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jcchikikomori** [aeberdinelli/atom-idea#1]
I am trying a new function based on the specified function used (will be based)

[Enter steps to reproduce:]

1. Copy the whole function (folded)
2. Paste it everywhere inside the file

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-idea](https://github.com/aeberdinelli/atom-idea) package 1.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\USER\.atom\packages\atom-idea\lib\helpers\get_func.js:41

TypeError: Cannot read property 'length' of undefined
    at exports.default (/packages/atom-idea/lib/helpers/get_func.js:41:35)
    at Object.getSuggestions (/packages/atom-idea/lib/atom-idea.js:44:28)
    at providers.forEach.provider (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1674:32)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1811:30)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1358:25)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:3191:53)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:3165:42)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1357:23)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1323:23)
    at TextEditor.object.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:1647:30)
```

### Commands

```
  3x -0:28.6.0 editor:newline (input.hidden-input)
     -0:27.5.0 intentions:highlight (input.hidden-input)
     -0:27.3.0 core:paste (input.hidden-input)
     -0:23.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:22.8.0 intentions:highlight (input.hidden-input)
 11x -0:22.2.0 core:select-right (input.hidden-input)
  2x -0:21.1.0 core:select-left (input.hidden-input)
     -0:20.5.0 intentions:highlight (input.hidden-input)
     -0:20.4.0 core:copy (input.hidden-input)
     -0:20.2.0 core:move-right (input.hidden-input)
     -0:19.7.0 core:backspace (input.hidden-input)
     -0:18.9.0 core:move-up (input.hidden-input)
     -0:10.6.0 snippets:next-tab-stop (input.hidden-input)
     -0:10.6.0 snippets:expand (input.hidden-input)
     -0:10.6.0 editor:indent (input.hidden-input)
  2x -0:08.7.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-ide-ui 0.7.2 
atom-idea 1.2.2 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
cakephp-snippets 0.6.1 
highlight-selected 0.13.1 
Hydrogen 2.2.2 
hyperclick-php 0.2.1 
ide-css 0.2.0 
ide-html 0.4.1 
ide-json 0.2.0 
ide-php 0.7.4 
indent-guide-improved 1.4.13 
intellij-idea-keymap 0.2.3 
intentions 1.1.5 
linter 2.2.0 
linter-erb 1.1.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
php-fmt 0.1.2 
remote-ftp 2.1.4 
```

**Comment by jcchikikomori** [comment]
Restarting Atom fixed the problem
